services:
    alcalyn_flush_on_kernel_terminate.listener:
        class: Alcalyn\FlushOnKernelTerminate\EventListener\KernelTerminateListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
            